### ISSUE TITLE
additional packages with conda failed

### ISSUE THREAD

**Issue by josiasbruderer** [aflueckiger/KED2021#1]
Hi Alex

Thanks for the installation guide! The installation worked (see my system configuration below). However I run into some issues, that might be relevant to address:

I had problems installing the additional packages with conda: spacy and textacy were not installed because of conflicts with other packages. (Solving environment took suuuper long to proceed, failed and then checked for conflicts - and found a lot!)

https://github.com/aflueckiger/KED2021/blob/master/materials/installation_guide.md#install-python-packages-all-systems
```bash
conda install flake8 #worked
conda install -c anaconda nodejs #worked
conda install -c anaconda spacy #failed
conda install -c conda-forge textacy #failed
conda install -c conda-forge plotnine #worked
```

What so ever, I managed to install spacy and textacy using pip. I hope that it will work correctly though!
```bash
pip install -U spacy
pip install textacy
```

And about kite: I'm not sure if this should be installed as root. I decided to install as normal user and it worked as well. 
```bash
#not: sudo bash -c "$(wget -q -O - https://linux.kite.com/dls/linux/current)"
bash -c "$(wget -q -O - https://linux.kite.com/dls/linux/current)"
```

So long, and thanks for all the snakes
Josias

---

**system configuration:**

- anaconda/2020.11-build-py38_0 
- conda/4.9.2 
- requests/2.24.0 
- CPython/3.8.5 
- Linux/5.10.18-1-MANJARO 
- manjaro/20.2.1 
- glibc/2.33

**Comment by aflueckiger** [comment]
Thanks for your feedback. Although it is about issues, I am glad to see students using GitHub actively.

Indeed, the installation of Kite should be performed without administration rights. It is leftover code when I tried to fix Kite on my system and I didn't intend to include this in the guide. I publish a new one shortly. Thanks!

Concerning the Python packages, I am not sure though. As you are using Manjaro Linux, you have installed many Python packages already using the pip package manager or you system manager (e.g., pacman). In order to avoid conflicting package dependencies, you either have to create virtual environments or using either pip or Anaconda exclusively. 

Personally, I don't see the point of using Anaconda on a Linux system. You may want to stick to pip. I am happy to chat about this in tomorrow's session.
